import test from 'node:test';import assert from 'node:assert/strict';
import {initialState,transition,dispatchEffect,ACTIONS} from '../skills/woia-communications/scripts/provider.mjs';
import {digest} from '../skills/woia-communications/scripts/guard.mjs';
import {kapsoAdapter,kapsoIngress} from '../skills/woia-communications/scripts/kapso.mjs';
const receive={conversation_id:'c',message_id:'m',source_ref:'e',subject_id:'s',contact_id:'contact',account_id:'account',channel:'whatsapp'};
const send={conversation_id:'c',subject_id:'s',contact_id:'contact',account_id:'account',channel:'whatsapp',generation:1,effect_id:'effect',delivery_key:'business-intent',content:'synthetic',content_version:'v1',business_origin:'task',to:'123'};
function pair(action,payload,id='op'){const c={action,payload,operation_id:id,organization:'org',resource:'c',purpose:'service'};const x={authenticated:true,actor:'agent',organization:'org',department:'customer-service',now:100,policy_version:'p1',source_current:true,adapter_verified:true,recipient:{resolved:true,organization:'org',subject_id:'s',contact_id:'contact',account_id:'account',channel:'whatsapp',purpose:'service',to:'123',class:'external',consent:true}};x.grant={action,command_digest:digest(c),actor:'agent',organization:'org',resource:'c',purpose:'service',expires_at:200,policy_version:'p1'};return [c,x];}
function run(state,action,payload,id){return transition(state,...pair(action,payload,id));}
const started=()=>run(initialState(),ACTIONS[0],receive,'in').state;
const prepared=()=>run(started(),ACTIONS[1],send,'out').state;
test('external ingress normalized into durable Interaction and deduplicated',()=>{const s=started();assert.equal(s.interactions.length,1);assert.equal(run(s,ACTIONS[0],receive,'repeat').result.status,'DUPLICATE');});
test('only Customer Service can execute ingress or external send',()=>{for(const [state,action,payload] of [[initialState(),ACTIONS[0],receive],[started(),ACTIONS[1],send]]){const [c,x]=pair(action,payload);x.department='finance';assert.throws(()=>transition(state,c,x),/CUSTOMER_SERVICE/);}});
test('external send creates intent not delivery and idempotent retry never duplicates effect',()=>{let s=prepared();assert.equal(s.effects[0].status,'prepared');s=run(s,ACTIONS[1],send,'out').state;assert.equal(s.effects.length,1);assert.throws(()=>run(s,ACTIONS[1],send,'different'),/DUPLICATE_EFFECT/);});
test('exact command change invalidates grant',()=>{const [c,x]=pair(ACTIONS[1],send);c.payload={...send,content:'changed'};assert.throws(()=>transition(started(),c,x),/EXACT_AUTHORITY/);});
test('distinct effect IDs across tasks cannot duplicate the stable business delivery intent',()=>{assert.throws(()=>run(prepared(),ACTIONS[1],{...send,effect_id:'second'},'second-op'),/DUPLICATE_DELIVERY/);});
test('revoked expired stale or missing source authority fail closed',()=>{for(const edit of [x=>x.grant.revoked=true,x=>x.grant.expires_at=100,x=>x.policy_version='p2',x=>x.source_current=false]){const [c,x]=pair(ACTIONS[1],send);edit(x);assert.throws(()=>transition(started(),c,x));}});
test('purpose scoped internal staff can be contacted by other departments',()=>{const [c,x]=pair(ACTIONS[2],send);x.department='finance';Object.assign(x.recipient,{class:'internal',relationship:'staff',authenticated:true,assignment_current:true,purpose_authorized:true});assert.equal(transition(started(),c,x).result.status,'PREPARED');});
test('authorized staff contact can initiate a new conversation without external ingress',()=>{const [c,x]=pair(ACTIONS[2],{...send,generation:0});x.department='people';Object.assign(x.recipient,{class:'internal',relationship:'staff',authenticated:true,assignment_current:true,purpose_authorized:true});const out=transition(initialState(),c,x);assert.equal(out.result.status,'PREPARED');assert.equal(out.state.conversations[0].generation,0);});
test('Customer Service can initiate a purpose-authorized consented external conversation',()=>{const out=run(initialState(),ACTIONS[1],{...send,generation:0});assert.equal(out.result.status,'PREPARED');});
test('vendor label inactive assignment unauthenticated and wrong purpose never bypass',()=>{for(const values of [{relationship:'vendor'},{assignment_current:false},{authenticated:false},{purpose_authorized:false},{purpose:'other'}]){const [c,x]=pair(ACTIONS[2],send);Object.assign(x.recipient,{class:'internal',relationship:'staff',authenticated:true,assignment_current:true,purpose_authorized:true},values);assert.throws(()=>transition(started(),c,x));}});
test('handoff and takeover suppress prepared effects and preserve already sent effects',()=>{for(const action of [ACTIONS[5],ACTIONS[6]]){const s=prepared();s.effects.push({...s.effects[0],effect_id:'sent',status:'sent'});const n=run(s,action,{conversation_id:'c',reason:'human',evidence_ref:'e',target_human:'h'},action).state;assert.equal(n.effects[0].status,'superseded');assert.equal(n.effects[1].status,'sent');assert.throws(()=>run(n,ACTIONS[1],{...send,effect_id:'new'},'new'),/TAKEOVER/);}});
test('new inbound generation invalidates obsolete queued contacts',()=>{const n=run(prepared(),ACTIONS[0],{...receive,message_id:'new'},'new-in').state;assert.equal(n.effects[0].status,'superseded');assert.throws(()=>run(n,ACTIONS[1],{...send,effect_id:'new'},'new-out'),/OBSOLETE/);});
function memoryStore(s){return {state:s,async transaction(org,fn){const next=structuredClone(this.state);const result=await fn(next);this.state=next;return result;}};}
test('dispatch reserves before I/O; unknown outcome remains durable and prevents blind retry',async()=>{const store=memoryStore(prepared());let calls=0;const args={store,organization:'org',effect_id:'effect',authorize:async()=>true,adapter:{send:async()=>{calls++;assert.equal(store.state.effects[0].status,'dispatching');throw Error('timeout');}}};assert.equal((await dispatchEffect(args)).status,'unknown');await assert.rejects(dispatchEffect(args),/RECONCILE/);assert.equal(calls,1);});
test('dispatch rechecks current authority and human conversation ownership',async()=>{const store=memoryStore(prepared());await assert.rejects(dispatchEffect({store,organization:'org',effect_id:'effect',authorize:async()=>false,adapter:{send:()=>{throw Error('must not call');}}}),/AUTHORITY/);assert.equal(store.state.effects[0].status,'prepared');});
test('unknown reconciliation proof permits bounded retry only after definitive not-sent',()=>{let s=prepared();s.effects[0].status='unknown';assert.throws(()=>run(s,ACTIONS[1],{...send,effect_id:'retry',retry_of:'effect'},'retry'),/RECONCILE/);const [c,x]=pair(ACTIONS[4],{conversation_id:'c',effect_id:'effect',account_id:'account',evidence_ref:'proof',outcome:'definitive-not-sent'},'rec');x.definitive_not_sent=true;s=transition(s,c,x).state;assert.equal(run(s,ACTIONS[1],{...send,effect_id:'retry',retry_of:'effect'},'retry').result.status,'PREPARED');});
test('found reconciliation and status maintain attributable provider identity',()=>{let s=prepared();s.effects[0].status='unknown';s=run(s,ACTIONS[4],{conversation_id:'c',effect_id:'effect',account_id:'account',evidence_ref:'proof',outcome:'found',provider_message_id:'remote'},'rec').state;s=run(s,ACTIONS[3],{conversation_id:'c',effect_id:'effect',account_id:'account',evidence_ref:'status',provider_message_id:'remote',status:'delivered'},'status').state;assert.equal(s.effects[0].status,'delivered');assert.throws(()=>run(s,ACTIONS[3],{conversation_id:'c',effect_id:'effect',account_id:'account',evidence_ref:'status',provider_message_id:'remote',status:'sent'},'regress'),/REGRESSION/);});
test('late submitted or unknown reconciliation never erases delivered/read receipt',()=>{for(const status of ['delivered','read'])for(const outcome of ['found','unknown']){const s=prepared();Object.assign(s.effects[0],{status,provider_message_id:'remote'});const n=run(s,ACTIONS[4],{conversation_id:'c',effect_id:'effect',account_id:'account',evidence_ref:'late',outcome,provider_message_id:'remote',status:'submitted'},'late').state;assert.equal(n.effects[0].status,status);assert.equal(n.effects[0].provider_message_id,'remote');}});
test('Kapso text adapter refuses unqualified binding and wrong account; mocked official SDK payload matches',async()=>{assert.throws(()=>kapsoAdapter({}),/QUALIFIED/);let payload;const a=kapsoAdapter({client:{messages:{sendText:async p=>{payload=p;return {messages:[{id:'remote'}]};}}},phoneNumberId:'phone',account_id:'account',qualification:{result:'PASS',account_id:'account'}});assert.equal((await a.send({...send,status:'dispatching'})).provider_message_id,'remote');assert.deepEqual(payload,{phoneNumberId:'phone',to:'123',body:'synthetic',previewUrl:false});await assert.rejects(a.send({...send,status:'dispatching',account_id:'other'}),/MISMATCH/);});
test('signed Kapso ingress requires verified exact account and stable source message',async()=>{const args={rawBody:Buffer.from('{}'),signature:'synthetic',appSecret:'synthetic',verifySignature:()=>false,normalizeWebhook:()=>({phoneNumberId:'phone',messages:[{id:'m',text:{body:'synthetic'}}]}),phoneNumberId:'phone',resolveRecipient:async()=>({...receive,resolved:true})};await assert.rejects(kapsoIngress(args),/SIGNATURE/);const out=await kapsoIngress({...args,verifySignature:()=>true});assert.equal(out[0].message_id,'m');});
